### PR TITLE
Sync with upstream main branch

### PR DESCRIPTION
**Pull request by joshpeterson**
This is an automatically generated pull request to merge changes from the upstream main branch.

### CODE REVIEW

**Comment by joshpeterson** [comment]
I'll ignore this one pending our discussion of CI stability in this repo.

**Comment by hez2010** [comment]
> CI stability

I think you may only want to merge the commit which successfully passed the tests and produced the artifact.
The latest successful runtime commit can be accessed [here](https://aka.ms/dotnet/7.0.1xx/daily/productCommit-win-x64.txt).

**Comment by joshpeterson** [comment]
> > CI stability
> 
> I think you may only want to merge the commit which successfully passed the tests and produced the artifact. The latest successful runtime commit can be accessed [here](https://aka.ms/dotnet/7.0.1xx/daily/productCommit-win-x64.txt).

Interesting - is there documentation about when this commit is updated? I'm wondering how often that is.

**Comment by hez2010** [comment]
>  is there documentation about when this commit is updated

It's the official nightly build. See https://github.com/dotnet/installer

> I'm wondering how often that is.

Once a day if CI passed.

**Comment by joshpeterson** [comment]
Thanks for the suggestion - we'll look into this as an option.

**Pull request closed without merging**
